# Generated by Django 4.2.5 on 2023-10-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="Django", max_length=100),
        ),
        migrations.AddField(
            model_name="projects",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.category",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
