# Generated by Django 4.2.5 on 2023-10-06 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_projects_tools_used_projects_skills_used_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skills",
            name="project",
        ),
        migrations.RemoveField(
            model_name="tools",
            name="project",
        ),
    ]
