# Generated by Django 4.2.5 on 2023-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_remove_skills_project_remove_tools_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="name",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="first_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="last_name",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
