# Generated by Django 4.2.5 on 2023-10-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_coursesandcertificates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesandcertificates",
            name="certificate_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
