# Generated by Django 4.2.5 on 2023-10-13 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_alter_coursesandcertificates_certificate_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
