# Generated by Django 4.2.5 on 2023-10-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_blogs_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="title",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
