# Generated by Django 4.2.5 on 2023-10-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_portfolio_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="colleagues",
            name="is_approve",
            field=models.BooleanField(default=False),
        ),
    ]
