# Generated by Django 4.2.5 on 2023-10-23 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0015_alter_colleagues_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="colleagues",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
