# Generated by Django 4.2.5 on 2023-10-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0017_alter_colleagues_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="image",
        ),
        migrations.AddField(
            model_name="blogs",
            name="caption",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name="Project_Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects_images")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projects",
                    ),
                ),
            ],
        ),
    ]
