# Generated by Django 4.2.5 on 2023-10-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0018_remove_projects_image_blogs_caption_project_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.project_images",
            ),
        ),
    ]
