# Generated by Django 4.2.5 on 2023-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0021_alter_projects_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects_images"),
        ),
        migrations.DeleteModel(
            name="Project_Images",
        ),
    ]
