# Generated by Django 4.2.5 on 2023-10-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0022_alter_projects_image_delete_project_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="video_poster",
            field=models.ImageField(blank=True, null=True, upload_to="video_posters"),
        ),
    ]
