# Generated by Django 4.2.5 on 2023-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0023_projects_video_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="bio_2",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
