# Generated by Django 4.2.5 on 2023-11-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0026_alter_skills_icon_alter_tools_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesandcertificates",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images"),
        ),
    ]
