# Generated by Django 4.2.5 on 2023-11-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0027_coursesandcertificates_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesandcertificates",
            name="certificate_link",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="coursesandcertificates",
            name="course_link",
            field=models.URLField(max_length=2000),
        ),
    ]
