# Generated by Django 4.2.5 on 2023-11-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0028_alter_coursesandcertificates_certificate_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesandcertificates",
            name="certificate_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="coursesandcertificates",
            name="course_link",
            field=models.URLField(max_length=500),
        ),
    ]
