# Generated by Django 4.2.5 on 2023-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0029_alter_coursesandcertificates_certificate_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesandcertificates",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
