# Generated by Django 4.2.5 on 2023-11-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0030_alter_coursesandcertificates_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesandcertificates",
            name="title",
            field=models.TextField(max_length=200),
        ),
    ]
