# Generated by Django 4.2.5 on 2023-11-05 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0033_coursesandcertificates_end_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoursesAndCertificates",
            new_name="Courses",
        ),
    ]
