# Generated by Django 4.2.5 on 2023-11-07 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0035_alter_blogs_caption_alter_blogs_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Courses",
        ),
    ]
