# Generated by Django 4.2.5 on 2023-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0036_delete_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("course_link", models.URLField(max_length=500)),
                (
                    "course_image",
                    models.ImageField(blank=True, null=True, upload_to="course_images"),
                ),
                (
                    "certificate_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("description", models.TextField(max_length=1000)),
                ("start_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("end_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
