# Generated by Django 4.2.5 on 2023-11-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0038_projectsimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="main_projects_images"
            ),
        ),
    ]
