# Generated by Django 4.2.5 on 2023-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0039_alter_projects_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
