# Generated by Django 4.2.5 on 2023-12-01 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0040_alter_courses_end_date_alter_courses_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"ordering": ["-start_date"]},
        ),
    ]
