# Generated by Django 4.2.5 on 2023-12-01 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0041_alter_courses_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"ordering": ["start_date"]},
        ),
    ]
