# Generated by Django 4.2.5 on 2023-12-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0042_alter_courses_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.TextField(max_length=4000),
        ),
    ]
