# Generated by Django 4.2.5 on 2023-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0043_alter_projects_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tools",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
