# Generated by Django 4.2.5 on 2023-12-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0044_tools_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="skills",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
